### ISSUE TITLE
Notes feature is not working

### ISSUE THREAD

**Issue by ammonshepherd** [csbailey5t/prosody_theme_rewrite#11]
Some poems have a "note" associated with a line. The feature should add a lightbulb icon at the end of a line when the line has been completed (meter, foot, stress are correctly completed). Clicking on the lightbulb icon should show a pop up note with text from the "note" field.

This was working in the previous version.

**Comment by xferguson** [comment]
It looks like this only checks stress at the moment: handler.js193-201

`````
    if ( scheme === realAnswer ) {
        $("#checkstress" + lineNumber + " img").attr("src", correctAnswerUrl);
        showNote(lineNumber);
    } else if ( scheme === expectedAnswer) {
        $("#checkstress" + lineNumber + " img").attr("src", expectedAnswerUrl);
        showNote(lineNumber);
    } else {
        $("#checkstress" + lineNumber + " img").attr("src", incorrectAnswerUrl);
    }
`````

I know it's been a while, but do you recall when it was working so we can peek at the old code?

**Comment by xferguson** [comment]
It might be helpful to have `checkstress`, `checkmeter`, and `checkfeet` all return a boolean, so we can abstract the `showNote` call out of the check `checkstress` function and just run a `checkline` function that then calls the note if everything passes.

**Comment by xferguson** [comment]
Another approach, probably with longer-term stability, would be to abstract the poem itself into a js object and give the lines states. Then checking stress, getting stress state, and setting stress state would be a faster computation. This is a bigger task, however.

**Comment by xferguson** [comment]
I just noticed that since this issue is actually related to [handler.js](https://github.com/scholarslab/prosody_plugin/blob/master/js/handlers.js), the issue should be in that repo. I will open the issue in that repo, link to this one, an then provide some solutions. I recommend closing this issue.
