### ISSUE TITLE
transfer todo file to issues?

### ISSUE THREAD

**Issue by xferguson** [csbailey5t/prosody_theme_rewrite#16]
[this todo.md file](https://github.com/scholarslab/prosody_theme/blob/master/todo.md) seems to have one unresolved item. I don't have context for this item, but can it be turned into an issue (with more detail) so we can remove the file from the repo?

Here is the list as it currently stands:

> ~~Set line breaks after Tucker and after English in footer - Have done this, not sure if it looks better with line breaks or without~~
> 
> ~~Try putting Rules of Thumb up into main nav menu - duplicate this rather than delete it.~~
> 
> ~~Hopkins The Windhover - not ready for production~~
> 
> Add some contact info for errors or do browser check and message for incompatible browsers
> 
> ~~Make documentation on adding poems very accessible in wordpress~~
> 
> ~~See about sorting author by last name alphabetically - single field with last name, first name, explode and reverse in template. Are there any authors with esq. or jr. or III or something? Could put semicolon after last name + bit, explode on that, then explode on commas within.~~
> 
> ~~Fix Caesura spacing~~
> 
> ~~Look into size breaks at small widths - currently won't fix.~~
>

**Comment by jeremyboggs** [comment]
This seems covered by #24, and #7 and #8. Closing.
