### ISSUE TITLE
Migrate items from utility.js to plugin repo

### ISSUE THREAD

**Issue by xferguson** [csbailey5t/prosody_theme_rewrite#20]
There are a few items here that could arguably be in the plugin repo, such as the meter-select dialog box. These things need to be explored and then the right things should be moved over.

Looking at this does unveil some potential design limitations where the dialog popup should potentially by a builtin prosodyJS function that can be called by js in the theme, the method likely being setup at initialization.

This also reveals that some of the jQuery ui tools may be plugin dependencies at the moment, instead of theme dependencies. This should be taken into account as things are re-arranged.

**Comment by xferguson** [comment]
@mossiso Do you have any views on this?

**Comment by jeremyboggs** [comment]
Fixed in 6df4f97e36776467e0d12010921d61034f490ee6.

**Comment by xferguson** [comment]
Thanks @jeremyboggs for the merge. As I look again at my original notes for the issue, I had mentioned the jQuery ui tools, which I did nothing to modify or migrate. Maybe this warrants a discussion, or just a simple move and label in the dependencies. Just don't want to accidentally drop the ball there.
